# Generated by Django 5.2.6 on 2025-11-10 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freepigeon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='lojaproduto',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='lojaproduto',
            name='loja',
        ),
        migrations.RemoveField(
            model_name='lojaproduto',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='pedido',
        ),
        migrations.AlterUniqueTogether(
            name='pedidoproduto',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='carrinho',
            name='data_adicao',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='valor_total',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='avaliacao_media',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='cor',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='peso',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='tamanho',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='carrinho',
        ),
        migrations.AddField(
            model_name='carrinho',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='carrinho',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='freepigeon.usuario'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='categorias/'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='endereco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='freepigeon.endereco'),
        ),
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/'),
        ),
        migrations.AlterField(
            model_name='carrinhoproduto',
            name='carrinho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='freepigeon.carrinho'),
        ),
        migrations.AlterField(
            model_name='carrinhoproduto',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data_efetuado',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(default='Pendente', max_length=50),
        ),
        migrations.AlterField(
            model_name='pedidoproduto',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='freepigeon.pedido'),
        ),
        migrations.AlterField(
            model_name='pedidoproduto',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='ProdutoAtributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=255)),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freepigeon.atributo')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributos', to='freepigeon.produto')),
            ],
            options={
                'unique_together': {('produto', 'atributo')},
            },
        ),
        migrations.DeleteModel(
            name='Avaliacao',
        ),
        migrations.DeleteModel(
            name='LojaProduto',
        ),
        migrations.DeleteModel(
            name='Pagamento',
        ),
        migrations.RemoveField(
            model_name='pedidoproduto',
            name='desconto_aplicado',
        ),
    ]
