# Generated by Django 5.2.6 on 2025-11-24 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freepigeon', '0003_alter_usuario_cpf_alter_usuario_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='freepigeon.usuario'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='loja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='freepigeon.loja'),
        ),
    ]
