# Generated by Django 5.2.6 on 2025-11-26 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freepigeon', '0004_produto_vendedor_alter_produto_loja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='endereco',
        ),
        migrations.AddField(
            model_name='endereco',
            name='apelido',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='endereco',
            name='principal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='endereco',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='freepigeon.usuario'),
        ),
    ]
