# Generated by Django 5.2.6 on 2025-12-04 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freepigeon', '0005_remove_usuario_endereco_endereco_apelido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('preco_mensal', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('limite_anuncios', models.PositiveIntegerField(blank=True, help_text='Número máximo de anúncios ativos. Deixe vazio para ilimitado.', null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Plano padrão para novos usuários / login Google.')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='plano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='freepigeon.plano'),
        ),
    ]
