# Generated by Django 5.2.6 on 2025-12-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freepigeon', '0006_plano_usuario_plano'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
