# Generated by Django 5.2.6 on 2025-12-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freepigeon', '0008_adminuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
